package com.example.weatherforecast.utils

const val  API_KEY = "2796b36d9abe5f41d72a45968f612366"
const val ICON_URL = "https://openweathermap.org/img/wn/"
const val SEARCH_URL = "https://nominatim.openstreetmap.org/search"
 const val PREFS_NAME = "settings"
 const val LANGUAGE_KEY = "language"
 const val UNIT = "unit"
 const val SPEED = "speed"
 const val LOCATION = "location"
 const val LAT = "lat"
 const val LNG = "lng"
 const val CURRLAT = "currlat"
 const val CURRLNG = "currlng"
 const val CITY = "city"
 const val ENABLENOTIFY = "notifi"